site_name: Aarohi Elysium Commercial and Housing Cooperative Service Society Ltd.
repo_url: https://github.com/rkpatel1474/AarohiElysiumSociety

theme:
  name: material
  logo: assets/Images/white_logo.png
  features:
    - navigation.expand

plugins:
  - search
  - pdf-export:
      combined: true
      media_type: print
      combined_output_path: "./pdfs/AarohiElysium.pdf"

  - with-pdf:
        # author: Applied Software Pvt Ltd
        # copyright: © 2024
        cover: true
        back_cover: true
        cover_title: Aarohi Elysium Commercial and Housing Cooperative Service Society Ltd.
        cover_subtitle: (REG/AHD/SA(HAA)19885/2024)
        custom_template_path: .docs/assets/css/extra.css
        toc_title: Table of Content
        heading_shift: true
        toc_level: 2
        ordered_chapter_level: 3
        #excludes_children:
        #    - 'release-notes/:upgrading'
        #    - 'release-notes/:changelog'
        #
        #exclude_pages:
        #    - 'bugs/'
        #    - 'appendix/contribute/'
        #convert_iframe:
        #    - src: IFRAME SRC
        #      img: POSTER IMAGE URL
        #      text: ALTERNATE TEXT
        #    - src: ...
        #two_columns_level: 3
        #
        #render_js: true
        #headless_chrome_path: headless-chromium
        #
        output_path: ./pdfs/AarohiElysium.pdf
        #enabled_if_env: ENABLE_PDF_EXPORT
        #
        # debug_html: true
        #show_anchors: true
        #verbose: true

extra_css:
  - assets/css/extra.css


nav:  # Custom navigation for the sidebar
  - Introduction: index.md
  - Rule Book:
    - General: 02_GeneralRules.md
    - Safety: 03_Safety.md
    - Driving: 04_Driving.md
    - Security: 05_Security.md
    - Shifting In/Out: 06_Shifting.md
    - Visitors: 07_Visitors.md
    - Parking: 08_Parking.md
    - Lifts: 09_Lifts.md
    - Gymnasium: 10_Gymnasium.md
    - Swimming Pool: 11_SwimmingPool.md
    - Parties | Functions: 12_PartiesFunction.md
    - House Keeping: 13_HouseKeeping.md
    - Alterations: 14_Alterations.md
    - Flat on Rent: 15_FlatRent.md
    - Maintenance Charges: 16_Maintenance.md
    - Transfer or Sale of Flat: 17_SaleFlat.md
    - Servants: 18_Servants.md
    - Annextures: 
      - Overview: 19_Annextures.md
      - Penalties | Fines : 20_Fines.md




